theme: jekyll-theme-minimal
title: Christopher Becom
description: Lead / Senior Mobile Developer
logo: [images/avatar.jpeg]
show_downloads: ["false"]
google_analytics: [Your Google Analytics tracking ID]