# Site settings
title: Christopher Becom
description: Lead / Senior Mobile Engineer
url: "https://cnbecom.github.io"

# Social settings
500px_url:
facebook_url: https://facebook.com/cnbecom
github_url: https://github.com/cnbecom
linkedin_url: https://www.linkedin.com/cnbecom
twitter_url: https://twitter.com/cnbecom

# Build settings
markdown: kramdown
