title: Christopher Becom
logo: /assets/img/avatar.jpeg
description: Lead / Senior Mobile Software Engineer
google_analytics:
theme: jekyll-theme-minimal
show_downloads: false
show_twitter: true
show_linkedin: true
show_angelco: true 
show_stackoverflow: true